### ISSUE TITLE
[Bug] 'LockState' has not been declared — compilation failure with ESPHome 2026.4.x

### ISSUE THREAD

**Issue by MaTyXon** [rednblkx/HAP-ESPHome#62]
**Describe the bug**
Compilation fails with `'LockState' has not been declared` in `homekit/lock.cpp:416` when using HAP-ESPHome with ESPHome 2026.4.x. ESPHome 2026.x appears to have moved the `LockState` type into a full namespace (`esphome::lock::LockState`), but `lock.cpp` in HAP-ESPHome still references it without the namespace qualifier, causing a compilation error.

There are also two warnings that will become breaking errors in ESPHome 2026.6:
```
WARNING cv.only_with_esp_idf was deprecated in 2026.1, will change behavior in 2026.6.
Use cv.only_on_esp32 and/or cv.only_with_arduino instead.
```

**To Reproduce**
1. Use HAP-ESPHome `@main` with a lock entity and `pn532_spi` as `nfc_id` for HomeKey
2. Compile with ESPHome 2026.4.2
3. Compilation fails at `lock.cpp:416`

Full error log:
```
src/esphome/components/homekit/lock.cpp: In member function 'virtual void esphome::homekit::LockEntity::setup()':
src/esphome/components/homekit/lock.cpp:416:16: error: 'LockState' has not been declared
  416 |         [this](LockState /* state */) { LockEntity::on_lock_update(ptrToLock); });
      |                ^~~~~~~~~
*** [.pioenvs/.../homekit/lock.cpp.o] Error 1
========================= [FAILED] Took 49.01 seconds =========================
```

**Expected behavior**
The project should compile cleanly with ESPHome 2026.4.x with no errors related to `LockState`.

**Screenshots**
N/A — full error log included above.

**Additional context**
- Device: ESP32 (esp32dev board)
- ESPHome version: 2026.4.2
- HAP-ESPHome: latest `@main`
- Framework: ESP-IDF 5.5.4
- PN532: pn532_spi (SPI mode, as required by HomeKey)

**Workaround:** Commenting out `nfc_id`, `on_hk_success` and `on_hk_fail` in the `homekit: lock:` block allows compilation — HomeKit lock control works but HomeKey NFC is disabled.

Happy to test any fix!

**Comment by rednblkx** [comment]
Hi,

just pushed a fix (0f8bac3af082c5c393645df9667d4331b890a2d2)
